### ISSUE TITLE
Incomplete Cloud Formation Template Mapping?

### ISSUE THREAD

**Issue by Christopheraburns** [mozilla/hubs-ops#116]
Beginning on line 3351 of stack.yaml:

`ImageId: !FindInMap [Regions, !Ref "AWS::Region", ImageId]`

However, the Mapping does not contain a Second level Key called ImageID:

`Mappings:
  Regions:
    us-east-1:
      Abbreviation: USE1
    us-west-1:
      Abbreviation: USW1
    us-west-2:
      Abbreviation: USW2
    us-east-2:
      Abbreviation: USE2
    ap-northeast-1:
      Abbreviation: APN1
    eu-west-1:
      Abbreviation: EU`

It appears the AMI-ID is missing?  My CFT Stack fails at line 3351.

**Comment by justincolangelo** [comment]
@Christopheraburns I am seeing the same issue. I uploaded the stack file to S3 and created a new CF stack using that template. After creating a changeset it fails to build with that error. Is there something I am missing? I am not sure the order of operations with this repo. Did you end up finding a solution?

**Comment by Christopheraburns** [comment]
@justincolangelo  - I did not find a solution.  I assumed what @Pattersonbl2 posted on 12/2 to be the case.  The problem is I don't know what services/configurations are installed/made on the AMI they have omitted.  I tried to spin up a vanilla Ubuntu instance, but the AMI they have omitted seems to have services and or components needed to complete the install.
@Pattersonbl2  - can you share the AMI configuration with us?
