### ISSUE TITLE
Stack creation was failed

### ISSUE THREAD

**Issue by illusorr** [mozilla/hubs-ops#123]
Hi,
`Hubs Cloud Personal` deployment on AWS t3.medium was failed with rollback status as follow:

```
Resource handler returned message: "The runtime parameter of python2.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 621ae781-f305-41ad-bf0b-8de702413834, Extended Request ID: null)" (RequestToken: d7da230e-db6c-a5ed-d967-0bb779a5ddf4, HandlerErrorCode: InvalidRequest)
```
![image](https://user-images.githubusercontent.com/92729925/138571673-b2797a59-b618-4b6c-bacb-222191c9479c.png)

the version was 1.1.2 .
can you give me any idea to resolve this?
Cheers!

**Comment by Pattersonbl2** [comment]
This issue was resolved. we have updated the template in AWS but is currently creating another issues
