### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by kunguz** [mozilla/hubs-ops#79]
Hi, I tried Mozilla hubs thanks to IEEEVR 2020 last week. I am amazed with the quality and want to start doing something using hubs. What I have in mind is a simple task: an avatar bot that comes with a menu to turn on/off a LED connected to a Rpi. I basically don't know where to start with hubs. Need some directions/suggestions here on where to start...

**Comment by blairmacintyre** [comment]
For discussion and help with doing things with Hubs, I suggest following the community link on the hubs.mozilla.com home page to join the Discord server.  There's a lively and active community (including both the hubs team and people using it for all sorts of things) that you can discuss things with!

**Comment by kunguz** [comment]
Thank you @blairmacintyre , will start investigating discord server. Once again thanks for the fast response!
